// SVG icons for Asset and Mint cards
import assetMintCover from "../../assets/img/drops/mint-card-cover-1.png";
import assetStatusIcon from "../../assets/img/drops/drop-asset-status.png";

// Drops page asset mint cards
export const assetMintCard = [
    {
        thumb: assetMintCover,
        statsIcon: assetStatusIcon,
        type: "Legendary",
        coins: "5 ETH",
        price: "$25.36",
        cardName: "Anubis",
        holderSupply: "Holders Supply Remaining",
        holderSupplyData: "295/300",
        totalSupply: "Total Supply Remaining",
        totalSupplyData: "295/300",
        mintType: "Mint",
    },
    {
        thumb: assetMintCover,
        statsIcon: assetStatusIcon,
        type: "Legendary",
        coins: "5 ETH",
        price: "$25.36",
        cardName: "Anubis",
        holderSupply: "Holders Supply Remaining",
        holderSupplyData: "295/300",
        totalSupply: "Total Supply Remaining",
        totalSupplyData: "295/300",
        mintType: "Mint",
    }, {
        thumb: assetMintCover,
        statsIcon: assetStatusIcon,
        type: "Legendary",
        coins: "5 ETH",
        price: "$25.36",
        cardName: "Anubis",
        holderSupply: "Holders Supply Remaining",
        holderSupplyData: "295/300",
        totalSupply: "Total Supply Remaining",
        totalSupplyData: "295/300",
        mintType: "Mint",
        assetMintedSuccess:false
    }, {
        thumb: assetMintCover,
        statsIcon: assetStatusIcon,
        type: "Legendary",
        coins: "5 ETH",
        price: "$25.36",
        cardName: "Anubis",
        holderSupply: "Holders Supply Remaining",
        holderSupplyData: "295/300",
        totalSupply: "Total Supply Remaining",
        totalSupplyData: "295/300",
        mintType: "Mint",
        assetMintedSuccess: true,
    }, {
        thumb: assetMintCover,
        statsIcon: assetStatusIcon,
        type: "Legendary",
        coins: "5 ETH",
        price: "$25.36",
        cardName: "Anubis",
        holderSupply: "Holders Supply Remaining",
        holderSupplyData: "295/300",
        totalSupply: "Total Supply Remaining",
        totalSupplyData: "295/300",
        mintType: "Mint",
        assetMintedSuccess: false,
    },
    {
        thumb: assetMintCover,
        statsIcon: assetStatusIcon,
        type: "Legendary",
        coins: "5 ETH",
        price: "$25.36",
        cardName: "Anubis",
        holderSupply: "Holders Supply Remaining",
        holderSupplyData: "295/300",
        totalSupply: "Total Supply Remaining",
        totalSupplyData: "295/300",
        mintType: "Open",
    },

];