// SVG icons
import settingCardBgShape from "../../assets/svg/profile/setting-game-card-bg.svg";

// Styles used in the component
export const styles = {
    settingGamenautCard: {
        padding: "0px",
        height: "100%",
    },
    settingGamenautCardHeader: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        padding: "30px",
    },
    settingGamenautHeadIc: {
        display: "flex",
        alignItems: "center",
        gap: "16px",
        "& img": {
            width: "36px",
            height: "36px",
            borderRadius: "50px",
        },
    },
    settingGamenautCardBody: {
        background: `url(${settingCardBgShape}) no-repeat`,
        backgroundSize: "100%",
        padding: "25px 30px 20px",
        display: "flex",
        flexDirection: "column",
        gap: "10px",
        position: "relative",
        "&:before": {
            content: `""`,
            position: "absolute",
            background: "var(--gradient-pink-border)",
            boxShadow: "3px 0px 18px #3FC2EA",
            borderRadius: "26px 26px 0px 0px",
            width: "47%",
            height: "4px",
            top: 0,
            left: "5px",
        },
    },
    settingGamenautCardPrice: {
        fontWeight: 500,
        fontSize: "25px",
        lineHeight: "25px",
    },
    settingGamenautCardCompare: {
        display: "flex",
        alignItems: "center",
        gap: "4px",
        fontSize: "12px",
        lineHeight: "15px",
        opacity: "0.7",
    },
    settingGamenautCardNotify: {
        fontSize: "14px",
        lineHeight: "25px",
    },
    settingGamenautActions: {
        display: "flex",
        alignItems: "center",
        gap: "8px",
        background: "var(--gradient-primary)",
        WebkitBackgroundClip: "text",
        WebkitTextFillColor: "transparent",
        "& button": {
            padding: "0",
            gap: "8px",
        },
    },
    settingNotificationWrapper: {
        position: "relative",
        "&:after": {
            content: `""`,
            position: "absolute",
            bottom: "-100px",
            left: "100px",
            width: "370px",
            height: "260px",
            background: "var(--page-gradient-blue-dark)",
            mixBlendMode: "lighten",
            opacity: "0.35",
            filter: "blur(106px)",
            transform: "rotate(42.93deg)",
            zIndex: "-1",
        },
    },
    settingAccountWrapper: {
        position: "relative",
        "&:after": {
            content: `""`,
            position: "absolute",
            top: "-100px",
            right: "0px",
            width: "370px",
            height: "260px",
            background: "var(--page-gradient-blue-dark)",
            mixBlendMode: "lighten",
            opacity: "0.35",
            filter: "blur(106px)",
            transform: "rotate(42.93deg)",
            zIndex: "-1",
        },
    },
    settingAccountLinkingWrapper: {
        position: "relative",
        overflowY: "hidden",
        "&:after": {
            content: `""`,
            position: "absolute",
            bottom: "-100px",
            left: "50px",
            width: "370px",
            height: "260px",
            background: "var(--page-gradient-blue-dark)",
            mixBlendMode: "lighten",
            opacity: "0.35",
            filter: "blur(106px)",
            transform: "rotate(42.93deg)",
            zIndex: "-1",
        },
    },
    profileLaunchCard: {
        padding: "24px 20px",
        display: "flex",
        alignItems: "center",
        gap: "60px",
        justifyContent: "space-between",
    },
    profileLaunchLabels: {
        display: "flex",
        alignItems: "center",
        gap: "8px",
    },
    profileLaunchLabelLight: {
        fontSize: "14px",
        lineHeight: "25px",
        opacity: "0.7",
    },
    profileLaunchActions: {
        "& button": {
            display: "flex",
            alignItems: "center",
            gap: "8px",
        },
    },
};