
// SVG icons
import communityBG from "../../assets/svg/gameDetail/join-community-bg.svg";
import gameCoverBG from "../../assets/svg/gameDetail/game-cover.svg";

// Styles used in the component
export const styles = {
    dashboardWrapper: {
        background: "var(--body-bg-dark)",
        minHeight: "100vh",
        padding: "15px",
        position: "relative",
        color: "var(--white-color)",
        fontFamily: "var(--font-primary)",
    },
    mainWrapper: {
        width: "calc(100% - 255px)",
        marginLeft: "240px",
        padding: "15px",
    },
    gameCoverCard: {
        background: `url(${gameCoverBG})`, 
        backgroundSize: "cover",
        padding: "40px",
    },
    gameInfoCard: {
        display: "flex",
        alignItems: "center",
        gap: "25px",
        color: "var(--white-color)",
        marginTop: "200px",
        marginBottom: "25px",
    },
    gamePic: {
        width: "140px",
        height: "140px",
        borderRadius: "13px",
        filter: "drop-shadow(0px 8px 23px rgba(108, 93, 211, 0.25))",
        background: "var(--border-gradient-gray)",
        padding: "1px",
        position: "relative",
        "& img": {
            width: "140px",
            height: "140px",
            borderRadius: "13px",
        },
        "&::before": {
            content: `""`,
            position: "absolute",
            inset: "0",
            borderRadius: "13px",
            padding: "1px",
            background: "var(--border-gradient-gray)",
            WebkitMask: "linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0)",
            WebkitMaskComposite: "xor",
            MaskComposite: "exclude",
            zIndex: -1,
            "@-moz-document url-prefix()": {
                WebkitMaskComposite: "subtract",
            },
        },
    },
    category: {
        fontWeight: "700",
        fontSize: "11px",
        lineHeight: "22px",
        textTransform: "uppercase",
        background: "var(--gradient-primary)",
        backgroundClip: "text",
        WebkitBackgroundClip: "text",
        WebkitTextFillColor: "transparent",
        textShadow: "var(--text-shadow-primary)",
    },
    gameTitle: {
        fontFamily: "var(--font-primary)",
        fontWeight: "700",
        fontSize: "35px",
        lineHeight: "31px",
        color: "var(--white-color)",
        marginTop: "10px",
        "@media screen and (max-width: 991px)": {
            fontSize: "24px",
        },
    },
    gameBy: {
        fontWeight: "400",
        fontSize: "10px",
        lineHeight: "10px",
        color: "var(--white-color)",
        "& span": {
            color: "var(--pink-primary)",
            display: "inline-block",
            marginLeft: "4px",
        },
    },
    gameTags: {
        listStyle: "none",
        padding: 0,
        margin: "16px 0px 20px",
        "& li": {
            display: "inline-block",
            padding: "8px 25px !important",
            height: "auto",
            background: "var(--tag-bg-primary)",
            backdropFilter: "blur(10px)",
            borderRadius: "6px",
            position: "relative",
            "&::after": {
                content: `''`,
                position: "absolute",
                left: 0,
                top: 0,
                right: 0,
                bottom: 0,
                padding: "2px",
                borderRadius: "6px",
                background: "var(--gradient-primary)",
                mask: "var(--mask-gradient-primary)",
                webkitMask: "var(--mask-gradient-primary)",
                maskComposite: "destination-out",
                webkitMaskComposite: "destination-out",
                zIndex: -1,
                "@-moz-document url-prefix()": {
                    WebkitMaskComposite: "subtract",
                },
            },
            "&:not(:last-child)": {
                marginRight: "20px",
            },
        },
    },
    gameInfo: {
        fontWeight: "400",
        fontSize: "14px",
        lineHeight: "25px",
        color: "var(--white-color)",
        opacity: "0.7",
    },
    gameRequired: {
        padding: "0px 35px",
        marginTop: "30px",
        position: "relative",
        fontWeight: "500",
        fontSize: "10px",
        lineHeight: "17px",
        color: "var(--menu-color-grey)",
        "&::before": {
            content: `''`,
            position: "absolute",
            width: "5px",
            height: "40px",
            background: "var(--purple-dark)",
            borderRadius: "0px 26px 26px 0px",
            boxShadow: "var(--box-shadow-green)",
            left: 0,
        },
        "& span": {
            display: "block",
        },
    },
    
    gameDescriptionBox: {
        // background: "var(--glass-gradient-primary)",
        padding: "10px",
        borderRadius: "10px",
        "& img": {
            background: "var(--input-bg-dark)",
            boxShadow: "var(--input-box-shadow-light)",
            backdropFilter: "blur(213px)",
            width: "100%",
            borderRadius: "10px",
        },
    },
    gameDescBox: {
        marginTop: "25px",
    },
    descTitle: {
        fontFamily: "var(--font-primary)",
        fontWeight: 500,
        fontSize: "16px",
        lineHeight: "16px",
        color: "var(--white-color)",
        marginBottom: "15px",
    },
    descText: {
        fontWeight: 400,
        fontSize: "14px",
        lineHeight: "21px",
        color: "var(--white-color)",
        opacity: "0.7",
        maxWidth: "95%",
        marginBottom: "24px",
    },

    // Gallery Slider styles
    gameGalleryWrapper: {
        position: "relative",
        "&:after": {
            content: `""`,
            position: "absolute",
            width: "379.04px",
            height: "306.25px",
            background: "var(--page-gradient-green-1)",
            mixBlendMode: "lighten",
            opacity: "0.3",
            filter: "blur(91px)",
            transform: "rotate(147.94deg)",
            top: "0px",
            right: "100px",
        },
    },
    gallerySlideWrapper: {
        "& img": {
            width: "100%",
        },
        "& .slick-slide": {
            padding: "10px",
            background: "rgba(34, 34, 36, 0.3)",
            boxShadow: "0px 19px 68px #151517",
            backdropFilter: "blur(213px)",
            borderRadius: "10px",
            transition: "0.4s all ease-in",
            // width: "15% !important",
            "& img": {
                maxWidth: "100%",
                width: "100%",
                height: "325px",
                objectFit: "cover",
                borderRadius: "10px",
            },
        },
        "& .active": {
            // width: "40% !important",
        },
        "& .slick-arrow": {
            background: "var(--input-bg-dark)",
            backdropFilter: "blur(213px)",
            color: "var(--white-color)",
            right: 0,
            left: "auto",
            top: "-50px",
            width: "28px",
            height: "28px",
            borderRadius: "50px !important",
            padding: "0px !important",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            cursor: "pointer",
            "&::before": {
                content: `""`,
                position: "absolute",
                inset: "0",
                padding: "1px",
                background: "var(--gradient-dark-border)",
                WebkitMask: 
                "linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0)",
                WebkitMaskComposite: "xor",
                MaskComposite: "exclude",
                zIndex: -1,
                borderRadius: "50px !important",
                "@-moz-document url-prefix()": {
                    WebkitMaskComposite: "subtract",
                },
            },
            "&.slick-prev": {
                right: "35px",
            },
        },
    },
    // activeGallery: {
    //     width: "40% !important",
    // },

    // Gamefi detail styles
    gameFiDetailWrapper: {
        position: "relative",
        "&:before": {
            content: `""`,
            position: "absolute",
            width: "173.38px",
            height: "118.53px",
            background: "var(--page-gradient-blue-1)",
            mixBlendMode: "lighten",
            opacity: "0.7",
            filter: "blur(106px)",
            transform: "matrix(-0.72, 0.41, 1.12, 0.74, 0, 0)",
            top: "120px",
            left: "50%",
        },
        "& .slick-list": {
            padding: "0px !important",
        },
        "& .slick-arrow": {
            background: "var(--input-bg-dark)",
            backdropFilter: "blur(213px)",
            color: "var(--white-color)",
            right: 0,
            left: "auto",
            top: "0px",
            width: "28px",
            height: "28px",
            borderRadius: "50px !important",
            padding: "0px !important",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            cursor: "pointer",
            "&::before": {
                content: `""`,
                position: "absolute",
                inset: "0",
                padding: "1px",
                background: "var(--gradient-dark-border)",
                WebkitMask: 
                "linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0)",
                WebkitMaskComposite: "xor",
                MaskComposite: "exclude",
                zIndex: -1,
                borderRadius: "50px !important",
                "@-moz-document url-prefix()": {
                    WebkitMaskComposite: "subtract",
                },
            },
            "&.slick-prev": {
                right: "35px",
            },
        },
    },
    gameFiSlideIcons: {
        display: "flex",
        alignItems: "center",
        gap: "20px",
        marginTop: "50px",
    },
    gameFiDetailImg: {
        "& img": {
            maxWidth: "90%",
            width: "100%",
        },
    },
    gameFiTitle: {
        fontWeight: "500",
        fontSize: "16px",
        lineHeight: "30px",
        marginBottom: "16px",
        color: "var(--white-color)",
        textShadow: "none",
        fontFamily: "var(--font-primary)",
    },
    GameFiDescriptionText: {
        opacity: "0.7",
        marginBottom: "30px",
        fontSize: "14px",
        lineHeight: "25px",
        color: "var(--white-color)",
        fontFamily: "var(--font-primary)",
    },
    gameFiDetailList: {
        padding: 0,
        "& li": {
            paddingTop: 0,
            paddingBottom: "8px",
            paddingLeft: "20px !important",
            fontWeight: "400",
            fontSize: "14px",
            lineHeight: "21px",
            height: "auto",
            opacity: "0.7",
            position: "relative",
            "&:before": {
                content: `''`,
                position: "absolute",
                left: "0",
                top: 10,
                width: "8px",
                height: "8px",
                background: "var(--gradient-blue-border)",
                boxShadow: "3px 0px 18px #3FC2EA",
                borderRadius: "50px",
            },
        },
    },

    // Community card
    communityCardWrapper: {
        marginTop: "50px",
        background: `url(${communityBG}) no-repeat`,
        backgroundSize: "cover",
        backgroundPosition: "bottom center",
        backgroundColor: "var(--input-bg-dark)",
        backdropFilter: "blur(12px)",
        borderRadius: "8px",
        padding: "0px 0px 0px 50px",
        position: "relative",
        "&::before": {
            content: `""`,
            position: "absolute",
            inset: "0",
            borderRadius: "8px",
            padding: "1px",
            background: "var(--gradient-dark-border)",
            mask: "linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0)",
            WebkitMask: "linear-gradient(#fff 0 0) content-box, linear-gradient(#fff 0 0)",
            WebkitMaskComposite: "xor",
            maskComposite: "exclude",
            zIndex: "-1",
            "@-moz-document url-prefix()": {
                WebkitMaskComposite: "subtract",
            },
        },
        "& h4": {
            paddingLeft: 0,
        },
    },
    socialListCommon: {
        padding: "0",
        "& li": {
            display: "inline-block",
            paddingRight: "0",
            "& a": {
                display: "inline-block",
                width: "36px",
                height: "36px",
                borderRadius: "50px",
                border: "var(--social-icon-border)",
                background: "var(--social-icon-bg)",
                "& img": {
                    width: "100%",
                },
            },
            "&:not(:last-child)": {
                "& a": {
                    marginRight: "16px",
                },
            },
        },
    },

    newsGameWrapper: {
        position: "relative",
        overflow: "visible",
        "&:after": {
            content: `""`,
            position: "absolute",
            width: "225px",
            height: "154px",
            background: "var(--page-gradient-blue-1)",
            mixBlendMode: "lighten",
            opacity: "0.4",
            filter: "blur(106px)",
            transform: "matrix(-0.72, 0.41, 1.12, 0.74, 0, 0)",
            bottom: "-50px",
            right: "-100px",
            zIndex: "-1",
        },
    },
    newsList: {
        "& li": {
            display: "flex",
            alignItems: "flex-start",
            justifyContent: "space-between",
            paddingBottom: "15px",
            borderBottom: "1px solid var(--table-border)",
            height: "auto",
            "&:not(:first-of-type)": {
                paddingTop: "20px",
            },
        },
    },
    newsTitle: {
        fontFamily: "var(--font-primary)",
        fontWeight: "500",
        fontSize: "16px",
        lineHeight: "25px",
        maxWidth: "70%",
        "@media screen and (max-width: 991px)" : {
            maxWidth: "100%",
        },
    },
    newsActions: {
        marginTop: "15px",
        display: "flex",
        alignItems: "center",
        gap: "16px",
        "& p": {
            opacity: "0.7",
            fontSize: "12px",
            lineHeight: "14px",
            display: "flex",
            alignItems: "center",
            gap: "5px",
        },
    },
    newsCover: {
        padding: "0",
        "& img": {
            minHeight: "380px",
            width: "100%",
            objectFit: "cover",
        },
    },
    newsContent: {
        display: "flex",
        flexDirection: "column",
        height: "100%",
    },
    newsMainTitle: {
        fontWeight: "700",
        fontSize: "25px",
        lineHeight: "35px",
        marginBottom: "24px",
        color: "var(--white-color)",
        fontFamily: "var(--font-primary)",
    },
    newsDetailText: {
        lineHeight: "25px",
        opacity: "0.7",
        color: "var(--white-color)",
        fontFamily: "var(--font-primary)",
    },
    newsActionCard: {
        display: "flex",
        justifyContent: "space-between",
        marginTop: "auto",
    },
    newsDate: {
        fontSize: "14px",
        lineHeight: "25px",
        opacity: "0.7",
        color: "var(--white-color)",
        fontFamily: "var(--font-primary)",
    },

    // Announcements cards
   
    

    // Events
    eventDateTag: {
        padding: "10px 25px",
        fontSize: "10px",
        lineHeight: "15px",
        display: "inline-block",
        "&::before": {
            background: "var(--gradient-dark-border-2)",
        },
    },
    customEventListing: {
        paddingTop: "0",
        "& li": {
            marginBottom: "25px",
            color: "var(--white-color)",
            textDecoration: "none",
            padding: "14px 22px !important",
            display: "flex",
            alignItems: "center",
            gap: "20px",
            borderRadius: "10px",
            boxShadow: "var(--input-box-shadow-light)",
            height: "auto",
            "&:last-child": {
                marginBottom: "0",
            },
        },
    },
    customEventLogo: {
        "& img": {
            width: "50px",
            height: "50px",
            borderRadius: "10px",
        },
    },
    customEventTitle: {
        fontWeight: "500",
        fontSize: "16px",
        lineHeight: "24px",
        marginBottom: "8px",
        color: "var(--white-color)",
        textDecoration: "none",
        display: "block",
    },
    eventStats: {
        display: "flex",
        alignItems: "center",
        gap: "30px",
        "& img": {
            width: "16px",
            marginRight: "5px",
            "&.event-logo": {
                width: "12px",
            },
        },
    },
    eventActions: {
        display: "flex",
        alignItems: "center",
        marginLeft: "auto",
        gap: "20px",
        "& p": {
            opacity: "0.7",
            margin: 0,
            fontSize: "12px",
            lineHeight: "14px",
            textTransform: "uppercase",
        },
    },
    eventTeamTag: {
        padding: "5px 15px",
        display: "inline-flex",
        alignItems: "center",
        border: "var(--tag-border)",
        borderRadius: "9px",
        gap: "10px",
    },
}