name: Frontend Deploy

on:
  push:
    branches:
    - main
  workflow_dispatch:
    inputs:
      stage:
        type: choice
        description: Deploy mannually
        options:
          - Mannual Deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: yarn install
      - run: yarn deploy
